import {Island,PLOTS,TREES,ZONES,SPOTS} from './scene.js';
import {newState,restore,begin,tick,visit,unlock,sellOne,collectCoins,stationStep,EntryLatch,UPGRADE_INFO,upgradeCost,buyUpgrade} from './core.js';
document.title='浩劫好时光';
const $=s=>document.querySelector(s),KEY='haojie-life-save-v2';let state;
try{state=restore(localStorage.getItem(KEY)||localStorage.getItem('haojie-life-save-v1'));}catch{state=newState();}
let paused=true,loaded=false,pending=null,route=[],keys=new Set(),padInput={x:0,z:0},sound=true,audio,music,last=performance.now(),lastUI=0,lastSave=0,lastZone=0,stillTime=0,feedbackTimer,storageWarning=false,modalMode='intro';
const latch=new EntryLatch(),cooldowns=new Map(),modal=$('#modal');
const targets=[...PLOTS.map(([x,z],id)=>({kind:'plot',id,x,z,radius:.92})),...TREES.map(([x,z],id)=>({kind:'tree',id,x,z,radius:1.05}))];
let island;
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));}catch{if(!storageWarning){storageWarning=true;feedback('💾 ×');}}}
function feedback(symbol){$('#feedback').textContent=symbol;$('#feedback').classList.add('show');clearTimeout(feedbackTimer);feedbackTimer=setTimeout(()=>$('#feedback').classList.remove('show'),1400);}
function chime(kind='generic'){if(!sound)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume();const notes={plant:[440,660],harvest:[523,784,1046],collect:[660,880],sell:[392,523],pay:[330,494],cook:[392,494],generic:[560]};const seq=notes[kind]||notes.generic,t=audio.currentTime;seq.forEach((frequency,i)=>{const o=audio.createOscillator(),g=audio.createGain(),at=t+i*.07;o.type='sine';o.frequency.value=frequency;g.gain.setValueAtTime(.045,at);g.gain.exponentialRampToValueAtTime(.001,at+.11);o.connect(g).connect(audio.destination);o.start(at);o.stop(at+.12);});}catch{}}
function startMusic(){if(!sound)return;try{music??=$('#music');const src=new URL(state.weather==='night'?'./music/Pixel Whistle.mp3':'./music/Pixel Whistle (Remix).mp3',import.meta.url).href;if(!music.src.endsWith(src))music.src=src;music.volume=.3;music.play().catch(()=>{});}catch{}}
function applyWeather(){island.applyEnvironment(state.weather);startMusic();$('#weather').textContent=state.weather==='day'?'☀':state.weather==='rain'?'☂':'☾';}
function cycleWeather(){state.weather=state.weather==='day'?'rain':state.weather==='rain'?'night':'day';applyWeather();save();feedback(state.weather==='day'?'☀':state.weather==='rain'?'☂':'☾');}
function stopMusic(){if(music){music.pause();music.currentTime=0;}}
function emit(event,target){if(!event)return;island.feedback(event,target);if(event.type==='full')feedback('🐾 📦 ↗');else if(event.type==='pay'&&event.done)feedback('🔓 ✨');else chime(event.type==='plant'?'plant':event.type==='harvest'?'harvest':event.type==='collect'?'collect':event.type==='sell'?'sell':event.type==='pay'?'pay':event.type==='cook'?'cook':'generic');save();updateUI();}
function trigger(target){const key=target.kind+':'+target.id,now=performance.now();if(now-(cooldowns.get(key)||0)<400)return;cooldowns.set(key,now);emit(visit(state,target.kind,target.id),target);}
function findRoute(tx,tz){const step=.4,key=(x,z)=>`${x},${z}`,start={x:Math.round(island.actor.position.x/step),z:Math.round(island.actor.position.z/step)},goal={x:Math.round(tx/step),z:Math.round(tz/step)},nodes=new Map(),open=[{...start,g:0,f:0}],closed=new Set();nodes.set(key(start.x,start.z),open[0]);let lastNode;
 for(let count=0;open.length&&count<4500;count++){open.sort((a,b)=>a.f-b.f);const n=open.shift(),k=key(n.x,n.z);if(closed.has(k))continue;closed.add(k);if(n.x===goal.x&&n.z===goal.z){lastNode=n;break;}for(const[dx,dz]of[[1,0],[-1,0],[0,1],[0,-1],[1,1],[-1,-1],[1,-1],[-1,1]]){const x=n.x+dx,z=n.z+dz,nk=key(x,z);if(closed.has(nk)||!island.allowed(x*step,z*step)||!island.allowed((n.x+dx*.5)*step,(n.z+dz*.5)*step))continue;const g=n.g+Math.hypot(dx,dz);if(nodes.has(nk)&&nodes.get(nk).g<=g)continue;const node={x,z,g,f:g+Math.hypot(x-goal.x,z-goal.z),parent:n};nodes.set(nk,node);open.push(node);}}
 if(!lastNode)return null;const path=[];while(lastNode.parent){path.unshift({x:lastNode.x*step,z:lastNode.z*step});lastNode=lastNode.parent;}path.push({x:tx,z:tz});return path;}
function go(target){if(paused||!loaded)return;let dest=target;
 if(target.kind==='plot'||target.kind==='tree'){const match=targets.find(t=>t.kind===target.kind&&t.id===target.id);dest={...match};const p=target.kind==='plot'?state.plots[target.id]:state.trees[target.id];dest.stage=p.stage;}
 else if(target.kind==='post'||target.kind==='market')dest={kind:'ground',...ZONES.market};
 else if(target.kind==='kitchen'||target.kind==='station')dest={kind:'ground',...ZONES[target.id||'bread']};
 else if(target.kind==='home')dest={kind:'ground',x:-4.6,z:-3.4};
 else if(target.kind==='pet')return;
 if(!island.allowed(dest.x,dest.z))return;
 if(Math.hypot(dest.x-island.actor.position.x,dest.z-island.actor.position.z)<.95&&['plot','tree'].includes(dest.kind)){trigger(dest);return;}
 const path=findRoute(dest.x,dest.z);if(!path)return;pending=dest;route=path;advanceRoute();}
function advanceRoute(){const next=route.shift();if(next){island.setTarget(next.x,next.z);}else if(pending){const dest=pending;pending=null;if(['plot','tree'].includes(dest.kind)){const p=dest.kind==='plot'?state.plots[dest.id]:state.trees[dest.id];if(p.stage===dest.stage)trigger(dest);}}}
function updateUI(){$('#coins').textContent=Math.floor(state.coins);island.updateCrops(state);if(island.cargoRoot)island.updateCargo(state.cargo);const list=$('#upgrade-list');if(list){list.innerHTML=Object.entries(UPGRADE_INFO).map(([key,u])=>{const level=state.upgrades?.[key]||0,cost=upgradeCost(state,key),label=key==='field'?'扩展田地':key==='cooking'?'料理摊':key==='seeds'?'种子商店':u.name;return `<div class="upgrade-row"><div><b>${label}</b><br><span>等级 ${level}/${u.max}</span></div><button data-upgrade="${key}" ${cost===null||state.coins<cost?'disabled':''}>${cost===null?'满级':cost+' 金币'}</button></div>`;}).join('');}}
function zoneTick(){const pos=island.actor.position;
 for(const t of targets){const p=t.kind==='plot'?state.plots[t.id]:state.trees[t.id];if(stillTime>.45&&!p.unlocked&&Math.hypot(pos.x-t.x,pos.z-t.z)<t.radius){const ev=unlock(state,t.kind,t.id);emit(ev,t);if(ev?.done)trigger(t);}}
 if(stillTime>.45&&Math.hypot(pos.x-ZONES.market.x,pos.z-ZONES.market.z)<1.1){const count=state.groundCoins.length,angle=count*2.4,x=ZONES.market.x+.7+Math.cos(angle)*.2,z=ZONES.market.z+.85+Math.sin(angle)*.2;emit(sellOne(state,x,z),ZONES.market);}
 for(const[name,t]of Object.entries(ZONES)){if(stillTime<=.45||name==='market'||Math.hypot(pos.x-t.x,pos.z-t.z)>.83)continue;const station=state.stations[name];if(!station.unlocked)emit(unlock(state,'station',name),t);else emit(stationStep(state,name),t);}
const coins=collectCoins(state,pos.x,pos.z);for(const c of coins){island.fly('',new island.actor.position.constructor(c.x,.3,c.z),pos.clone().add(new island.actor.position.constructor(0,.65,0)),true);chime('collect');}if(coins.length){save();updateUI();}
}
function closeModal(){modal.hidden=true;paused=false;modalMode='';keys.clear();save();}
function openPause(){if(!loaded)return;paused=true;modalMode='pause';keys.clear();releasePad();modal.hidden=false;modal.querySelector('section').innerHTML='<div class="flower">☾</div><h1>歇一会儿</h1><div class="help"><b>走过去就可以。</b><br>经过田地：播种 → 离开再经过浇水 → 成熟后经过收获。点击同一田地也可继续下一步。<br>金色小麦、红色草莓、挂果榴莲表示成熟。<br>宠物托盘最多 24 件；走进金色出售圈自动卸货，靠近地面金币拾取。<br>站在金币地砖上自动投入金币解锁；中途离开保留已投入金额。<br>厨房两个区域分别做面包和奶昔：自动放入 2 份原料，取成品；冒黑烟要回来清理。<br>点击地面 / 摇杆 / WASD 移动。Esc 暂停。<br>不再强制日终结算，作物与树木持续保留。</div><button class="play" data-resume aria-label="继续游戏">▶</button><button class="reset" data-reset>重新开始…</button>';save();}
try{island=new Island($('#world'),go);}catch(e){$('#fatal').hidden=false;$('#fatal').textContent='3D 场景无法运行，请使用支持 WebGL 2 的浏览器。'+e.message;throw e;}
$('#start').addEventListener('click',()=>{begin(state);applyWeather();$('#sound').classList.toggle('on',sound);closeModal();updateUI();});
$('#pause').addEventListener('click',()=>{if(!state.started)return;if(paused&&modalMode==='pause')closeModal();else if(!paused)openPause();});
$('#sound').addEventListener('click',()=>{sound=!sound;$('#sound').classList.toggle('on',sound);if(sound){startMusic();chime();}else stopMusic();});
$('#weather').addEventListener('click',cycleWeather);
$('#upgrade-open').addEventListener('click',()=>{$('#upgrade-panel').hidden=false;updateUI();});$('#upgrade-close').addEventListener('click',()=>$('#upgrade-panel').hidden=true);$('#upgrade-list').addEventListener('click',e=>{const b=e.target.closest('[data-upgrade]');if(!b)return;const ev=buyUpgrade(state,b.dataset.upgrade);if(ev){feedback('✨');chime('pay');save();updateUI();}});
modal.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-resume'))closeModal();if(b.hasAttribute('data-reset')){modalMode='reset';modal.querySelector('section').innerHTML='<h1>重新开始？</h1><p>金币、作物、宠物货物与解锁进度将重置。</p><button class="secondary" data-resume>保留进度</button><button class="secondary" data-confirm>确认重置</button>';}if(b.hasAttribute('data-confirm')){state=newState();begin(state);latch.clear();cooldowns.clear();pending=null;route=[];island.walkTarget=null;island.actor.position.set(1.4,.155,4.4);closeModal();updateUI();}});
window.addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(k==='t'&&!e.repeat&&state.started)cycleWeather();if(['arrowup','arrowdown','arrowleft','arrowright',' '].includes(k))e.preventDefault();if(k==='escape'&&!e.repeat&&state.started){if(paused&&modalMode!=='intro')closeModal();else openPause();}if(!paused)keys.add(k);});window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));
const pad=$('#joystick');let pointer=null;function updatePad(e){const r=pad.getBoundingClientRect(),x=e.clientX-r.left-r.width/2,z=e.clientY-r.top-r.height/2,l=Math.hypot(x,z),m=Math.min(28,l);padInput={x:l?x/l*m/28:0,z:l?z/l*m/28:0};$('#stick').style.transform=`translate(${padInput.x*25}px,${padInput.z*25}px)`;}
function releasePad(){pointer=null;padInput={x:0,z:0};$('#stick').style.transform='';}
pad.addEventListener('pointerdown',e=>{if(paused)return;pointer=e.pointerId;pad.setPointerCapture(pointer);updatePad(e);});pad.addEventListener('pointermove',e=>{if(e.pointerId===pointer)updatePad(e);});for(const type of ['pointerup','pointercancel','lostpointercapture'])pad.addEventListener(type,releasePad);
window.addEventListener('blur',()=>{keys.clear();releasePad();});document.addEventListener('visibilitychange',()=>{if(document.hidden){save();if(state.started&&!paused)openPause();}});window.addEventListener('pagehide',save);
function frame(now){requestAnimationFrame(frame);const dt=Math.min(.08,(now-last)/1000);last=now;
 if(!paused&&loaded){const input={x:padInput.x+(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0),z:padInput.z+(keys.has('s')||keys.has('arrowdown')?1:0)-(keys.has('w')||keys.has('arrowup')?1:0)};if(Math.hypot(input.x,input.z)>.05){pending=null;route=[];}const oldPosition=island.actor.position.clone();const arrived=island.move(dt,input);stillTime=Math.hypot(oldPosition.x-island.actor.position.x,oldPosition.z-island.actor.position.z)<.005?stillTime+dt:0;latch.update(island.actor.position,targets,trigger);if(arrived)advanceRoute();tick(state,dt);if(now-lastZone>260){zoneTick();lastZone=now;}if(now-lastSave>2500){save();lastSave=now;}}
 if(now-lastUI>120){updateUI();lastUI=now;}island.render(now);}
requestAnimationFrame(frame);updateUI();let results;try{results=await island.load();}catch(error){console.error('3D 角色素材载入失败，改用临时角色。',error);if(!island.characters.rabbit)island.characters.rabbit=island.fallback(island.actor,1);if(!island.characters.pet)island.characters.pet=island.fallback(island.petActor,.58);if(!island.cargoRoot){island.cargoRoot=new (island.actor.constructor)();island.cargoRoot.position.set(0,.58,.47);island.petActor.add(island.cargoRoot);island.box(.65,.07,.49,0xb78e71,0,0,0,island.cargoRoot);for(const x of[-.31,.31])island.ball(.10,0xe6ba82,x,.56,.42,island.petActor);}results=[];}applyWeather();loaded=true;$('#start').disabled=false;$('#start').textContent='▶';$('#loading').textContent=results.every(x=>x==='fulfilled')?'':results.every(x=>x==='timeout')?'网络较慢，已启用轻量角色':'部分素材未载入，已使用临时角色';
if(new URLSearchParams(location.search).has('test'))window.__game={get state(){return state},get paused(){return paused},island,go,targets,advance(t){tick(state,t);updateUI();},snapshot(){return{...JSON.parse(JSON.stringify(state)),position:island.actor.position.toArray(),petPosition:island.petActor.position.toArray(),models:Object.keys(island.characters),stackCount:island.cargoRoot?.children.length-1,drawCalls:island.renderer.info.render.calls,triangles:island.renderer.info.render.triangles}},save,updateUI};
if('serviceWorker'in navigator&&isSecureContext)navigator.serviceWorker.register('./sw.js').catch(()=>{});
